// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmpEqqu-XvXxGLGa8delgxbpVxJW8rEIQ',
    appId: '1:741520299639:web:9a1d3255f8030a85c49872',
    messagingSenderId: '741520299639',
    projectId: 'personal-expense-c12f2',
    authDomain: 'personal-expense-c12f2.firebaseapp.com',
    storageBucket: 'personal-expense-c12f2.firebasestorage.app',
    measurementId: 'G-WXVZ2TCVES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPFXW_HNc-izdDVG_cN3n_WcvYtt0lPjE',
    appId: '1:741520299639:android:6f48e7f1897f33ebc49872',
    messagingSenderId: '741520299639',
    projectId: 'personal-expense-c12f2',
    storageBucket: 'personal-expense-c12f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFncLzBwHaUkGM27cX7ir724ZRyTw3V28',
    appId: '1:741520299639:ios:d3ba186c36714befc49872',
    messagingSenderId: '741520299639',
    projectId: 'personal-expense-c12f2',
    storageBucket: 'personal-expense-c12f2.firebasestorage.app',
    iosBundleId: 'com.example.personalExpense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFncLzBwHaUkGM27cX7ir724ZRyTw3V28',
    appId: '1:741520299639:ios:d3ba186c36714befc49872',
    messagingSenderId: '741520299639',
    projectId: 'personal-expense-c12f2',
    storageBucket: 'personal-expense-c12f2.firebasestorage.app',
    iosBundleId: 'com.example.personalExpense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmpEqqu-XvXxGLGa8delgxbpVxJW8rEIQ',
    appId: '1:741520299639:web:197e1d2ea278569fc49872',
    messagingSenderId: '741520299639',
    projectId: 'personal-expense-c12f2',
    authDomain: 'personal-expense-c12f2.firebaseapp.com',
    storageBucket: 'personal-expense-c12f2.firebasestorage.app',
    measurementId: 'G-T6E72JTM2W',
  );

}